version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BASE_URL=${BASE_URL}
      - ES_CERT_FINGERPRINT=${ES_CERT_FINGERPRINT}
      - ES_PASSWORD=${ES_PASSWORD}
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
